// generated by @ng-toolkit/universal
    const port = process.env.PORT || 3335;

    const server = require('./dist/server.js');

    server.app.listen(port, 'localhost', () => {
        console.log("Listening on: http://localhost:" + port );
    });

