// generated by @ng-toolkit/universal
    const port = process.env.PORT || 4200;

    const server = require('./dist/server.js');

    server.app.listen(port, () => {
        console.log("Listening on: http://localhost:" + port );
    });
